# Generated by Django 2.2.6 on 2019-11-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recieved', models.BooleanField()),
                ('is_agency', models.BooleanField()),
                ('agency_name', models.CharField(max_length=100, null=True)),
                ('mall_name', models.CharField(max_length=100, null=True)),
                ('is_clearance', models.BooleanField()),
                ('shipping_state_agency', models.CharField(max_length=100, null=True)),
                ('shipping_state_direct', models.CharField(max_length=100, null=True)),
                ('is_clearanceimpossible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
