# Generated by Django 2.2.6 on 2019-11-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returninfo',
            old_name='is_recieved',
            new_name='is_received',
        ),
    ]
