# Generated by Django 2.2.6 on 2019-11-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20191114_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returninfo',
            name='is_agency',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='returninfo',
            name='is_clearance',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='returninfo',
            name='is_clearanceimpossible',
            field=models.BooleanField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='returninfo',
            name='is_received',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
